### ISSUE TITLE
chef provision?

### ISSUE THREAD

**Issue by gliptak** [poise/yolover-example#1]
Would `chef provision/push` commands still be used with this approach?

https://blog.chef.io/2015/08/18/policyfiles-a-guided-tour/

Maybe a few examples lines could be added to the README.

Thanks

**Comment by coderanger** [comment]
I don't use `chef-provisioning` and recommend no one else uses it either (https://coderanger.net/provisioning/). As for `chef push`, that is all documented in the companion guide which you can find at https://yolover.poise.io/.
